export const labels = {
  en: {
    finalContext: "Final context selected for this answer",
    includeContext: "Include final context in the answer",
    eyebrow: "OFFICIAL EVIDENCE · LOCAL WORKSPACE",
    title: "Understand your Norwegian taxes.",
    intro: "Ask a question. Inspect the evidence. Keep the tax year in focus.",
    question: "Your tax question",
    placeholder: "What should I check before claiming a deduction?",
    year: "Tax year",
    unspecified: "Not specified",
    language: "Language",
    mode: "Retrieval mode",
    ask: "Find an answer",
    loading: "Working…",
    privacy:
      "Avoid names, identity numbers and other personal information. Questions are sent to your configured services.",
    disclaimer:
      "Research aid, not professional tax advice. Verify the original official sources before acting.",
    empty: "Your answer and its sources will appear here.",
    sources: "Sources cited in the answer",
    answer: "Answer",
    answered: "Evidence-based answer",
    clarification_required: "More information needed",
    abstained: "Insufficient evidence",
    failed: "Service unavailable",
    warnings: "Warnings",
    missing: "Missing information",
    confidence: "Model confidence (not calibrated)",
    error:
      "The request could not be completed. Check the API, indexed corpus and model services, then retry.",
    developer: "Developer retrieval inspector",
    inspect: "Compare retrieval",
    inspectorNote:
      "Runs a separate diagnostic query: dense, sparse, fused and reranked. Requires all retrieval services; this is not the exact answer trace. Scores across stages are not directly comparable.",
    noEvidence: "No evidence returned.",
    routing: "Routing decision",
    evidence: "Evidence chunks",
    yearNote: "Selecting a year does not guarantee that it is indexed.",
  },
  nb: {
    finalContext: "Endelig kontekst valgt for dette svaret",
    includeContext: "Inkluder endelig kontekst i svaret",
    eyebrow: "OFFISIELLE KILDER · LOKALT ARBEIDSOMRÅDE",
    title: "Forstå skatten din i Norge.",
    intro: "Still et spørsmål. Undersøk kildene. Velg riktig inntektsår.",
    question: "Ditt skattespørsmål",
    placeholder: "Hva bør jeg sjekke før jeg krever fradrag?",
    year: "Inntektsår",
    unspecified: "Ikke angitt",
    language: "Språk",
    mode: "Søkemodus",
    ask: "Finn et svar",
    loading: "Arbeider…",
    privacy:
      "Unngå navn, fødselsnummer og andre personopplysninger. Spørsmål sendes til tjenestene du har konfigurert.",
    disclaimer:
      "Forskningsverktøy, ikke profesjonell skatterådgivning. Kontroller de offisielle kildene før du handler.",
    empty: "Svaret og kildene vises her.",
    sources: "Kilder brukt i svaret",
    answer: "Svar",
    answered: "Kildebasert svar",
    clarification_required: "Mer informasjon nødvendig",
    abstained: "Utilstrekkelig kildegrunnlag",
    failed: "Tjenesten er utilgjengelig",
    warnings: "Advarsler",
    missing: "Manglende informasjon",
    confidence: "Modellens sikkerhet (ikke kalibrert)",
    error:
      "Forespørselen mislyktes. Kontroller API, indekserte dokumenter og modelltjenester, og prøv igjen.",
    developer: "Søkeinspektør for utviklere",
    inspect: "Sammenlign søk",
    inspectorNote:
      "Kjører et separat diagnostisk søk: dense, sparse, fused og reranked. Krever alle søketjenester; dette er ikke svarets eksakte spor. Poeng på tvers av trinn er ikke direkte sammenlignbare.",
    noEvidence: "Ingen kilder funnet.",
    routing: "Rutingsvalg",
    evidence: "Kildeutdrag",
    yearNote: "Et valgt år er ikke nødvendigvis indeksert.",
  },
  es: {
    finalContext: "Contexto final seleccionado para esta respuesta",
    includeContext: "Incluir contexto final en la respuesta",
    eyebrow: "FUENTES OFICIALES · ESPACIO LOCAL",
    title: "Entiende tus impuestos en Noruega.",
    intro: "Haz una pregunta. Revisa las fuentes. Ten presente el año fiscal.",
    question: "Tu pregunta fiscal",
    placeholder: "¿Qué debo comprobar antes de solicitar una deducción?",
    year: "Año fiscal",
    unspecified: "Sin especificar",
    language: "Idioma",
    mode: "Modo de retrieval",
    ask: "Buscar respuesta",
    loading: "Procesando…",
    privacy:
      "Evita nombres, números de identidad y otros datos personales. Las preguntas se envían a los servicios configurados.",
    disclaimer:
      "Herramienta de investigación, no asesoramiento fiscal profesional. Verifica las fuentes oficiales antes de actuar.",
    empty: "Aquí aparecerán la respuesta y sus fuentes.",
    sources: "Fuentes citadas en la respuesta",
    answer: "Respuesta",
    answered: "Respuesta basada en evidencia",
    clarification_required: "Se necesita más información",
    abstained: "Evidencia insuficiente",
    failed: "Servicio no disponible",
    warnings: "Advertencias",
    missing: "Información pendiente",
    confidence: "Confianza del modelo (no calibrada)",
    error:
      "No se pudo completar la solicitud. Comprueba la API, el corpus indexado y los modelos e inténtalo de nuevo.",
    developer: "Inspector de retrieval para desarrolladores",
    inspect: "Comparar retrieval",
    inspectorNote:
      "Ejecuta una consulta diagnóstica independiente: dense, sparse, fused y reranked. Requiere todos los servicios; no es la traza exacta de la respuesta. Las puntuaciones entre etapas no son directamente comparables.",
    noEvidence: "No se recuperaron evidencias.",
    routing: "Decisión de routing",
    evidence: "Fragmentos de evidencia",
    yearNote: "Seleccionar un año no garantiza que esté indexado.",
  },
};
export type Labels = typeof labels.en;
